source('../featurization.R')
setwd('..')
setwd('..')
setwd('..')
path = getwd()
#print(path)
inputFile = paste0(path,"/data-raw/sample_data.csv")
#inputFile = paste0(path,"/data-raw/FC_plus_RES_withPredictions.csv")
input = read.csv(inputFile)
featurelist = c("X30mer", "Percent.Peptide", "Amino.Acid.Cut.position", "G_20", "GC_Count","AA_18", "TT_17", "A", "GG", "predictions")
featuredata = featurization(input, featurelist)
#featuredata['AA_18']
