source('../loadData.R')
source('../viennaRNADataManipulation.R')
setwd('..')
setwd('..')
setwd('..')
dir = getwd()
filepath = paste0(dir,'/data-raw/sample_data.csv')
#viennaRNADataManipulation('sample_data.csv')
loadData(filepath)
