library(e1071)
library(DAAG)
library(h2o)
setwd('..')
setwd('..')
getpath = getwd()
#print(getpath)
mainpath = paste0(getpath,'/crisprpred_main/crisprpred_main.R')
source(mainpath)
featurepath = paste0(getpath,'/featurization/featurization.R')
source(featurepath)
metricpath = paste0(getpath,'/metrics/rmse.R')
source(metricpath)
formulapath = paste0(getpath, '/featureformula/featureformula.R')
source(formulapath)
svmreg = paste0(getpath,'/mlmethods/svmregression.R')
source(svmreg)
lmreg = paste0(getpath,'/mlmethods/lmregression.R')
source(lmreg)
dp = paste0(getpath, '/mlmethods/dplearning.R')
source(dp)
rf = paste0(getpath, '/mlmethods/randomforest.R')
source(rf)
ldata = paste0(getpath, '/loadData/loadData.R')
source(ldata)
viennaRna = paste0(getpath, '/loadData/viennaRNADataManipulation.R')
source(viennaRna)
setwd('..')
filepath = getwd()
inputFile = paste0(filepath,'/data-raw/sample_data.csv')
#inputFile = paste0(filepath,'/data-raw/FC_plus_RES_withPredictions.csv')
#print(inputFile)
featurelist = c("X30mer", "Percent.Peptide", "Amino.Acid.Cut.position", "G_20", "GC_Count","AA_18", "TT_17", "A", "GG", "MFE", "predictions")
kfoldCross = 2
crisprpred_main(inputFile, featurelist, kfoldCross, 2, 3, 0.59, 0.62)

